---
- name: Install repo
  hosts: all	
  gather_facts: no 	
  become: yes 	

  tasks:
  - name: install repo directory to remote server
    syncronize: 
      src: ../local_repo
      dest: /root/local_repo

